defaults:
  db_url: postgresql+psycopg2://postgres:pointLester@localhost:5432/hsr
  batch_size: 5000
  on_conflict: upsert           # options: append | upsert | fail

sources:
  - name: tax_csv
    type: csv
    path: real_estate_tax_balances_zip_code.csv
    target_table: 
    pk: [objectid]
    schema:
      objectid: int8
      zip_code: int4
      num_props: int4
      min_period: int4
      max_period: int4
      principal: float64
      interest: float64
      penalty: float64
      other: float64
      balance: float64
      avg_balance: float64
    rules:
      - rule: "zip_code >= 19019 and zip_code <= 19160"

  - name: lead_json
    type: json
    url: https://phl.carto.com/api/v2/sql?q=SELECT%20cartodb_id%20AS%20lead_id,%20zip_code,%20num_screen,%20num_bll_5plus,%20perc_5plus%20FROM%20child_blood_lead_levels_by_zip
    target_table: 
    pk: [lead_id]
    schema:
      id: int8
      zip_code: int4
      num_screen: int4
      num_bll_5plus: int4
      perc_5plus: float8
      data_redacted: bool
    rules:
      - rule: "zip_code >= 19019 and zip_code <= 19160"
      - rule: "perc_5plus <= 100"
      - rule: "num_screen >= 55"