defaults:
  db_url: postgresql+psycopg2://postgres:pointLester@localhost:5432/hsr
  batch_size: 5000
  on_conflict: upsert           # options: append | upsert | fail

sources:
  - name: tax_csv
    type: csv
    path: real_estate_tax_balances_zip_code.csv
    target_table: 
    pk: [objectid]
    schema:
      objectid: int
      zip_code: int
      num_props: int
      min_period: int
      max_period: int
      principal: float
      interest: float
      penalty: float
      other: float
      balance: float
      avg_balance: float
    rules:
      - rule: "zip_code >= 19019"
      - rule: "zip_code <= 19160"
      - rule: "zip_code NOT NULL"

  - name: lead_json
    type: json
    url: https://phl.carto.com/api/v2/sql?q=SELECT%20cartodb_id%20AS%20lead_id,%20zip_code,%20num_screen,%20num_bll_5plus,%20perc_5plus%20FROM%20child_blood_lead_levels_by_zip
    target_table: 
    pk: [lead_id]
    schema:
      id: int
      zip_code: int
      num_screen: int
      num_bll_5plus: int
      perc_5plus: float
      data_redacted: bool
    rules:
      - rule: "zip_code >= 19019"
      - rule: "zip_code <= 19160"
      - rule: "zip_code NOT NULL"